name: ${rootProject.name}
version: ${rootProject.version}
api-version: '1.21'
main: kr.r1atndud.Main
description: I made this because it was annoying to type everything one by one.
author: r1atndud

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0
  - org.jetbrains.kotlin:kotlin-reflect:2.0.0